pr: none
trigger: none

pool: pins-odt-agent-pool

variables:
  - group: pipeline_secrets

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: 11db266f4b2fa29f314a07fe0635f7b958d6f45f

jobs:
  - job: purge
    displayName: Cleanup Container Registry Images
    steps:
      - checkout: self
      - checkout: templates
      - script: |
          sudo apt-get install -y powershell
        displayName: 'Install PowerShell'
      - template: steps/azure_auth.yml@templates
        parameters:
          subscriptionId: edb1ff78-90da-4901-a497-7e79f966f8e2
      - template: steps/acr_purge.yml@templates
    workspace:
      clean: all
