parameters:
  - name: schemaMigration
    displayName: Run SQL Database Migration
    type: boolean
    default: true
  - name: seedData
    displayName: Add static (required) data to SQL database
    type: boolean
    default: false

pr: none
trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.18.1
  pipelines:
    - pipeline: build
      source: Build
      trigger:
        branches:
          include:
            - main

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    variableGroupPrefix: 'cd'
    environments:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Training
        dependsOn:
          - Test
      - name: Prod
        dependsOn:
          - Training
    globalVariables:
      - template: .azure/pipelines/azure-pipelines-variables.yml@self
    deploymentStages:
      - name: Deploy
        deploymentJobs:
          - name: Migrate
            condition: ${{ or(eq(parameters.schemaMigration, true), eq(parameters.seedData, true)) }}
            steps:
              - checkout: self
              - template: ../steps/azure_get_secrets.yml@templates
                parameters:
                  keyVaultName: pins-kv-crown-$(ENVIRONMENT)
                  secrets:
                    - name: crown-sql-admin-connection-string
                      variable: SQL_CONNECTION_STRING_ADMIN
                    - name: crown-sql-app-connection-string
                      variable: SQL_CONNECTION_STRING
              - template: ../steps/node_script.yml@templates
                parameters:
                  nodeVersion: 22
                  script: npm ci --workspace=@pins/crowndev-database
                  workingDirectory: $(Build.Repository.LocalPath)
              - ${{ if eq(parameters.schemaMigration, true) }}:
                  - template: ../steps/node_script.yml@templates
                    parameters:
                      nodeVersion: 22
                      environmentVariables:
                        SQL_CONNECTION_STRING_ADMIN: $(SQL_CONNECTION_STRING_ADMIN)
                      script: npm run migrate:prod
                      workingDirectory: $(Build.Repository.LocalPath)/packages/database
              - ${{ if eq(parameters.seedData, true) }}:
                  - template: ../steps/node_script.yml@templates
                    parameters:
                      nodeVersion: 22
                      environmentVariables:
                        SQL_CONNECTION_STRING: $(SQL_CONNECTION_STRING)
                      script: npm run seed:prod
                      workingDirectory: $(Build.Repository.LocalPath)/packages/database
          - name: Deploy Portal
            steps:
              - checkout: self
              - template: ../steps/azure_web_app_deploy.yml@templates
                parameters:
                  appName: pins-app-crowndev-portal-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  azurecrName: $(azurecrName)
                  repository: crowndev/portal
          - name: Deploy Manage
            steps:
              - checkout: self
              - template: ../steps/azure_web_app_deploy.yml@templates
                parameters:
                  appName: pins-app-crowndev-portal-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  azurecrName: $(azurecrName)
                  repository: crowndev/manage
