BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Contact] ALTER COLUMN [fullName] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Contact] ALTER COLUMN [telephoneNumber] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Contact] ALTER COLUMN [email] NVARCHAR(1000) NULL;

-- AlterTable
ALTER TABLE [dbo].[CrownDevelopment] ALTER COLUMN [eventId] NVARCHAR(1000) NULL;

-- AlterTable
ALTER TABLE [dbo].[Lpa] ALTER COLUMN [pinsCode] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Lpa] ALTER COLUMN [onsCode] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
