BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Representation] ADD [isAgent] BIT NOT NULL CONSTRAINT [Representation_isAgent_df] DEFAULT 1,
[isAgentAdult] BIT NOT NULL CONSTRAINT [Representation_isAgentAdult_df] DEFAULT 1;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
