BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Event] ALTER COLUMN [prepDuration] DECIMAL(6,2) NULL;
ALTER TABLE [dbo].[Event] ALTER COLUMN [reportingDuration] DECIMAL(6,2) NULL;
ALTER TABLE [dbo].[Event] ALTER COLUMN [sittingDuration] DECIMAL(6,2) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
