# Add this step after your Terraform Apply step in your pipeline
# This patches tags that are ignored by lifecycle rules in modules

- task: AzureCLI@2
  displayName: 'Patch App Service Tags'
  condition: and(succeeded(), ne(variables['Agent.JobStatus'], 'Failed'))
  inputs:
    azureSubscription: $(serviceConnectionName) # Use your service connection variable
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '$(Build.Repository.LocalPath)/infrastructure/scripts/patch-tags.sh'
    workingDirectory: '$(Build.Repository.LocalPath)'
  env:
    ENVIRONMENT: $(environment) # Pass environment if needed for conditional logic

# Alternative inline version if you prefer:
- task: AzureCLI@2  
  displayName: 'Patch App Service Tags (Inline)'
  condition: and(succeeded(), ne(variables['Agent.JobStatus'], 'Failed'))
  inputs:
    azureSubscription: $(serviceConnectionName)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    workingDirectory: '$(Build.Repository.LocalPath)/infrastructure'
    inlineScript: |
      set -e
      echo "=== Patching App Service Tags ==="
      
      # Get resource IDs from Terraform outputs
      APP_MANAGE_ID=$(terraform output -raw app_manage_id)
      APP_PORTAL_ID=$(terraform output -raw app_portal_id)
      
      echo "Updating manage app tags..."
      az resource update --ids "$APP_MANAGE_ID" --set \
          tags.CriticalityRating="Level 100" \
          tags.PersonalData="Yes" \
          tags.CreatedBy="devops"
      
      echo "Updating portal app tags..."
      az resource update --ids "$APP_PORTAL_ID" --set \
          tags.CriticalityRating="Level 2" \
          tags.PersonalData="Yes" \
          tags.CreatedBy="devops"
          
      echo "=== Tag patching complete ==="