trigger:
  branches:
    include:
      # trigger for merge queue branches
      - gh-readonly-queue/*

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - infrastructure

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    gitFetchDepth: 0
    validationJobs:
      - name: Check Commits
        steps:
          - script: mkdir -p $(Pipeline.Workspace)/.npm
            displayName: Ensure NPM cache directory exists
          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)" | package-lock.json
              path: $(Pipeline.Workspace)/.npm
            displayName: Cache NPM
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm ci
              environmentVariables:
                npm_config_cache: $(Piepline.Workspace)/.npm
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm run commitlint
